-- ==========================================================================
-- SQL DATABASE SCHEMA - AI INTERVIEW COACH
-- ==========================================================================
-- This file contains all the SQL commands needed to build your database and tables.
-- You can run these commands in MySQL Workbench, phpMyAdmin, or your command-line interface.

-- 1. Create the Database
-- Checks if the database already exists. If not, it creates a new one named "ai_interview_coach".
CREATE DATABASE IF NOT EXISTS ai_interview_coach;

-- Switch to using this database
USE ai_interview_coach;

-- 2. Create the "users" Table
-- Stores user credentials, email, and security role.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,          -- Unique ID, auto-incremented by MySQL
    username VARCHAR(50) NOT NULL UNIQUE,          -- Unique username, cannot be empty
    password VARCHAR(255) NOT NULL,                -- Encrypted password hash
    email VARCHAR(100) NOT NULL UNIQUE,            -- Unique email address
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER', -- Access role (ROLE_USER / ROLE_ADMIN)
    created_at DATETIME NOT NULL                   -- Account registration timestamp
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Create the "resumes" Table
-- Stores details extracted and analyzed from PDF resumes by Gemini AI.
CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,                       -- Links to the users table
    file_name VARCHAR(255) NOT NULL,               -- Original name of the PDF file
    skills TEXT,                                   -- Stores comma-separated or JSON list of skills
    projects TEXT,                                 -- Stores extracted projects
    ai_strengths TEXT,                             -- Detailed strengths generated by Gemini
    ai_weaknesses TEXT,                            -- Detailed weaknesses generated by Gemini
    created_at DATETIME NOT NULL,
    -- FOREIGN KEY: Ensures referential integrity. 
    -- If a user is deleted, their associated resumes will be automatically deleted (ON DELETE CASCADE).
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Create the "questions" Table
-- Stores dynamic practice questions generated by Gemini AI.
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,                 -- e.g., "Java", "Spring Boot", "SQL", "React", "DSA", "HR"
    question_text TEXT NOT NULL,                   -- The actual question
    difficulty VARCHAR(20) NOT NULL,               -- "BEGINNER", "INTERMEDIATE", "ADVANCED"
    sample_answer TEXT                             -- AI-generated ideal reference answer
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Create the "mock_interviews" Table
-- Tracks simulated mock interview sessions, scores, and granular feedback.
CREATE TABLE IF NOT EXISTS mock_interviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,                 -- Tech category tested
    score INT NOT NULL,                            -- Scaled score out of 100
    ai_feedback TEXT,                              -- Comprehensive review paragraphs from AI
    qa_records TEXT,                               -- JSON formatted record of questions asked & user's inputs
    created_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Create the "study_plans" Table
-- Stores personalized 7-day or 30-day study roadmaps.
CREATE TABLE IF NOT EXISTS study_plans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    duration_days INT NOT NULL,                    -- 7 or 30 days
    title VARCHAR(100) NOT NULL,                   -- Heading of the plan
    roadmap_json TEXT,                             -- Day-by-day JSON details
    created_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
